# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk: openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false
services:
  - postgresql


cache:
  directories:
    - $HOME/.m2

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

  env:
    global:
      - CODECOV_TOKEN="d9239f7f-e9bf-43da-aa7c-88655cafdec0"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - maksimus.s@mail.ru
    on_success: never # default: change
    on_failure: always # default: always





