CREATE TABLE post (
   id SERIAL PRIMARY KEY,
   name TEXT
);

CREATE TABLE candidate (
   id SERIAL PRIMARY KEY,
   name TEXT
);

CREATE TABLE photo(
   id SERIAL PRIMARY KEY
);

ALTER TABLE candidate ADD COLUMN photoId INTEGER REFERENCES photo(id) ON DELETE SET NULL;

ALTER TABLE candidate DROP COLUMN photoId;

ALTER TABLE photo ADD COLUMN name TEXT;


